/*
 * conf_motors.h
 *
 * Created: 14.07.2014 11:01:18
 *  Author: magne.normann
 */ 


#ifndef CONF_MOTORS_H_
#define CONF_MOTORS_H_

#include <asf.h>

#define CONF_MOTORS_MODULE			EXT2_PWM4CTRL_MODULE

#define CONF_MOTORS_LEFT_CHANNEL	EXT2_PWM4CTRL_0_CHANNEL
#define CONF_MOTORS_LEFT_OUTPUT		EXT2_PWM4CTRL_0_OUTPUT
#define CONF_MOTORS_LEFT_OUT_PIN	EXT2_PWM4CTRL_0_PIN
#define CONF_MOTORS_LEFT_OUT_MUX	EXT2_PWM4CTRL_0_MUX

#define CONF_MOTORS_RIGHT_CHANNEL	EXT2_PWM4CTRL_1_CHANNEL
#define CONF_MOTORS_RIGHT_OUTPUT	EXT2_PWM4CTRL_1_OUTPUT
#define CONF_MOTORS_RIGHT_OUT_PIN	EXT2_PWM4CTRL_1_PIN
#define CONF_MOTORS_RIGHT_OUT_MUX	EXT2_PWM4CTRL_1_MUX


#endif /* CONF_MOTORS_H_ */